// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpJwnkjTLAiqaaNCX6yrLJSLPeL8YraQc',
    appId: '1:913947853252:web:2b6e0bccf070d4c1bae491',
    messagingSenderId: '913947853252',
    projectId: 'oauth-upload-6c2e6',
    authDomain: 'oauth-upload-6c2e6.firebaseapp.com',
    storageBucket: 'oauth-upload-6c2e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7dKFzDwjI9w1fwqeAJYeNYO4FEAgi8A',
    appId: '1:913947853252:android:d0f97c213ca6a915bae491',
    messagingSenderId: '913947853252',
    projectId: 'oauth-upload-6c2e6',
    storageBucket: 'oauth-upload-6c2e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaU2CvPgD46iPDcExW1I3ryw7h-KBxO58',
    appId: '1:913947853252:ios:07f3644860c6ad52bae491',
    messagingSenderId: '913947853252',
    projectId: 'oauth-upload-6c2e6',
    storageBucket: 'oauth-upload-6c2e6.appspot.com',
    iosClientId: '913947853252-0jh7upeq24j5hi3f3a5rutlckh4othiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.oauthFileUpload',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaU2CvPgD46iPDcExW1I3ryw7h-KBxO58',
    appId: '1:913947853252:ios:07f3644860c6ad52bae491',
    messagingSenderId: '913947853252',
    projectId: 'oauth-upload-6c2e6',
    storageBucket: 'oauth-upload-6c2e6.appspot.com',
    iosClientId: '913947853252-0jh7upeq24j5hi3f3a5rutlckh4othiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.oauthFileUpload',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpJwnkjTLAiqaaNCX6yrLJSLPeL8YraQc',
    appId: '1:913947853252:web:f871206cd8044449bae491',
    messagingSenderId: '913947853252',
    projectId: 'oauth-upload-6c2e6',
    authDomain: 'oauth-upload-6c2e6.firebaseapp.com',
    storageBucket: 'oauth-upload-6c2e6.appspot.com',
  );
}
